cluster helpers
hytest-org/hytest pull request #197
Opened 2023-01-31 20:44 UTC by gzt5142

closes #189

2023-01-31 20:45 UTC, gzt5142 commented
helper notebooks created... now on to demo how they are used/imported.

2023-02-06 21:59 UTC, gzt5142 commented
OK... I think I have these working as I described when we talked about it last week. 

I worked the DScore and StandardSuite streamflow tutorials to use the helpers stored in environment_set_up.

2023-02-07 16:34 UTC, amsnyder requested changes
I think we should have the helpers all in one folder (maybe with a README if it isn't too much work to give a short description of the environments for each helper) and then link to that folder in the notebook so that users can see what their environment options are - otherwise, this looks good!

Also found two typos - I would have committed them, but I couldn't suggest these changes in the UI for the file `model_evaluation/tutorials/nwm_streamflow/01_Data_Prep.ipynb` because the diff was too big to load in my browser. If you make the change to the folder structure on your own branch, can you fix the typos too?

2023-02-07 17:28 UTC, gzt5142 commented
> I think we should have the helpers all in one folder (maybe with a README

I'm confused by this.  They are in the same folder: All the new helpers are in `./environment_set_up`, _as directed_. This is where I was told to put them when we talked about this on our team call. If this is no longer the right spot, then we should talk about where that might be. 

As to a README... I for-sure can expand the existing readme in this folder to describe what these are. Or write one in the new location, once that is determined.

2023-02-07 17:33 UTC, amsnyder commented
> > I think we should have the helpers all in one folder (maybe with a README
> 
> I'm confused by this. They are in the same folder: All the new helpers are in `./environment_set_up`, _as directed_. This is where I was told to put them when we talked about this on our team call. If this is no longer the right spot, then we should talk about where that might be.
> 
> As to a README... I for-sure can expand the existing readme in this folder to describe what these are. Or write one in the new location, once that is determined.

Right, they should be in `environment_set_up`! My want is for a user to have a quick way to see what helpers are available to them. I was suggesting we group the helper notebooks into a new sub-directory `environment_set_up\helpers` and add a readme to describe each option. If it's a pain to move them, we could just update the README in `environment_set_up` to describe these helper functions in general and then list the options. Then we might want to link to this README in the notebook so that someone using the notebook could quickly figure out how to adapt if they move to a new computing environment.

2023-02-08 16:57 UTC, gzt5142 commented
Short blurb in the environment setup readme.

2023-02-14 22:23 UTC, amsnyder commented
@gzt5142 can I change the name of `model_evaluation/tutorials/nwm_streamflow/02_Analysis_NWM.ipynb` to `model_evaluation/tutorials/nwm_streamflow/02_Analysis_StdSuite.ipynb`? I will also update the fp for where you read in the helper there since we updated that name.

2023-02-15 22:20 UTC, amsnyder commented on environment_set_up/README.md
> -If your workflow makes use of parallelism using Dask on HPC hosts, read [this](./tallgrass_dask-jobqueue.md)
Should we also delete the ./tallgrass_dask-jobqueue.md file? Do we want to link to this notebook here for better understanding instead? https://github.com/hytest-org/hytest/blob/main/essential_reading/Parallel_Dask.ipynb

2023-02-15 22:35 UTC, amsnyder approved these changes

2023-02-15 22:35 UTC, merged