Reviewed and updated forcings notebook 2
hytest-org/hytest pull request #451
Opened 2024-04-04 22:03 UTC by alaws-USGS

- Updated setup of Dask cluster
- Updated examples of exporting files
- Updated ending text to file
- Added functions to assist in create per station stat calculations for HCN dataset

2024-04-08 17:33 UTC, sfoks commented
This is great so far.

I have a minor edits to markdown language:
- 1st markdown cell: remove the "(to add: tmin, tmax, radiation components)" from the bullet point labeled 'Variables'.
- 2nd markdown cell: Replace QHUB w/ something more generic like "cloud-based jupyterhub (i.e., ESIP-Nebari)."
- 4th MD cell: We may want to just link to the hytest repo/jupyter book that [explains the data types/locs ](https://hytest-org.github.io/hytest/dataset_catalog/README.html) so we don't have to update this explanation in the future, and then just explain something along the lines of "for explanation of data naming and storage locations, please see [link]. You will want to use data for where you are working (i.e., if you are working on a cloud-based jupyterhub, you will want to use data stored on the cloud)."
- 5th MD cell: I think this may need some instructions for a user. I would adjust the title to be more generic so "You can setup your client and dataset for the compute environment you are working on" - then I would add some language about "adjusting the dataset name below to correspond to the dataset of interest you are working on. For this tutorial, we are focusing on the CONUS404 hourly dataset".
- 7th MD cell: We should remove the Hytest Sharepoint link since its internal to USGS only and cite the [CONUS404 variable descriptions](https://rda.ucar.edu/datasets/ds559.0/documentation/#) from NCAR.

Some questions about code cells:
- I wasn't able to access PRISM V2 in ESIP-Nebari. I was thrown a Forbidden error, potentially PRISM V2 needs AWS permissions? If so, we will want to mention that in the markdown cell above or consider putting PRISM V2 on OSN for tutorials and for hytest Eval team if we are running into this issue.
- In the points reference data section, trying to clip the points to DRB, I am getting "IndexError: list index out of range" on 
![image](https://github.com/hytest-org/hytest/assets/40471889/dfba46d3-5d7e-4e93-8c32-6e8e31538f53)

2024-04-12 14:15 UTC, hpodzorski-USGS commented
@alaws-USGS please see needed edits

2024-04-12 14:17 UTC, hpodzorski-USGS requested changes

2024-04-12 14:17 UTC, hpodzorski-USGS commented on evaluation/tutorials/CONUS404/2_CONUS404_DRB_Analysis.ipynb
> +    "import math\n",
`import cf_xarray`

2024-05-10 14:18 UTC, hpodzorski-USGS approved these changes

2024-05-10 14:18 UTC, merged