Ll 477
hytest-org/hytest pull request #500
Opened 2024-07-08 10:56 UTC by lluddenusgs

# Pull Request Code Review

## Overview
To add functionality to the model_eviz app by, adding a slidebar, and search functionality to the model via the site_no
## Links
- *Issues*: Close #477 
- *Inputs*: User's desired settings for the app (such as map, particular points)
- *Outputs*: User's desired output based on input

## Summary of Changes

- Sidebar added, 478 logic started, 477 finished

## How to Run
Standard mamba panels app setup

## Peer Reviewer Expectations

Expect workaround logic, not finalized logic flows, yet basic functionality met. 
## Not expected in Review

- issue 478 content 

## Next steps

2024-07-15 23:20 UTC, alaws-USGS requested changes

2024-07-15 23:20 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
> +
Add a description such as this
`description="Enter a column delimited list e.g. 01022500, 01022502"`

2024-07-15 23:20 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
> +subset = ['nldi','swim','gfv1d1','camels']
Let's add this constant to the config.py and called it something like STREAMGAGE_SUBSET

2024-07-15 23:20 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
This works and that is a great first step. Great work!

2024-07-16 16:00 UTC, lluddenusgs commented on apps/model_eval_viz/app.py
>  # Create a map template including rough borders for a start
Deleted lines 49-52 as discussed

2024-07-16 16:00 UTC, alaws-USGS requested changes

2024-07-16 16:00 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
>  # Create a map template including rough borders for a start
`gv_us`

2024-07-16 21:46 UTC, alaws-USGS requested changes

2024-07-16 21:46 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
> +def display_points(state_list:list=state_selector.value,ids:str=entered_points.value, data_set:str=subset_selector.value)->gv.Points:
I beleive you can delete all of the default values here as these will be passed by the pn.rx() function. 

You can then update data_set = data_set, as that will be passed by pn.rx().

2024-07-16 21:46 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
>  # create a DynamicMap to allow Panel to link map_selector with a Geoviews(Holoviews under the hood) object
update comment to use pn.rx() instead of DynamicMap

2024-07-16 21:46 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
>  # create a DynamicMap to allow Panel to link state_selector with a Geoviews(Holoviews under the hood) object
update comment to use pn.rx() instead of DynamicMap

2024-07-16 21:46 UTC, alaws-USGS commented on apps/model_eval_viz/app.py
>  # create a DynamicMap to allow Panel to link state_selector with a Geoviews(Holoviews under the hood) object
update comment to use pn.rx() instead of DynamicMap

2024-07-16 21:46 UTC, alaws-USGS commented
@lluddenusgs Delete lines 68-69 as we are no longer using `gv_us`

2024-07-17 14:40 UTC, alaws-USGS approved these changes

2024-07-17 14:42 UTC, merged